TimeBankWebApplication/TimeBankWebApplication/Controllers/RequestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeBankWebApplication.Helpers;
using TimeBankWebApplication.Models;

namespace TimeBankWebApplication.Controllers
{
    public class RequestsController : Controller
    {
        private const int _itemsOnPage = 6;
        private const int _pagesOnPagination = 5;
        private ApplicationContext _dbContext;
        private IOptions<AppSettings> _settings;
        private readonly ILogger<AccountController> _logger;

        public RequestsController(ApplicationContext dbContext, IOptions<AppSettings> settings,
                                 ILogger<AccountController> logger)
        {
            _dbContext = dbContext;
            _settings = settings;
            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> MyRequests()
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    var user = await _dbContext.Users.Include(u => u.Requests).ThenInclude(r => r.Orders)
                        .Include(u => u.Requests).ThenInclude(r => r.Category)
                        .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                    if (user != null)
                    {
                        return View(user.Requests);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Requests - MyRequests - Error: {ex.Message}");
                    return BadRequest();
                }
                return NotFound();
            }
            return NotFound();
        }

        public async Task<IActionResult> AllRequests(int? page)
        {
            List<Request> requests = new List<Request>();
            List<User> users = new List<User>();
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    users = await _dbContext.Users
                        .Include(u => u.Requests).ThenInclude(r => r.Category)
                        .Include(u => u.Requests).ThenInclude(r => r.Orders)
                        .Where(u => u.UserName != User.Identity.Name).ToListAsync();
                }
                else
                    users = await _dbContext.Users
                        .Include(u => u.Requests).ThenInclude(r => r.Category)
                        .Include(u => u.Requests).ThenInclude(r => r.Orders)
                        .ToListAsync();
                requests = (from user in users
                            from request in user.Requests
                            where !request.IsDone && request.ActiveOrder == null && request.IsActive
                            select request).ToList();
                return GetPagination(page, requests, "AllRequests", null, false, "AllRequests");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - AllRequests - Error: {ex.Message}");
                return BadRequest();
            }
        }

        [Authorize]
        public async Task<IActionResult> Add()
        {
            if (!User.Identity.IsAuthenticated)
                return BadRequest();
            try
            {
                var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                if (user == null)
                    return BadRequest();
                Request request = new Request
                {
                    User = user
                };
                ViewData["CategoryId"] = GetCategoriesSelectList();
                return View(request);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - Add - Error: {ex.Message}");
                return BadRequest();
            }
        }

        private List<SelectListItem> GetCategoriesSelectList(string selectedValue = null)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            try
            {
                list = _dbContext.Categories.Select(item => new SelectListItem
                {
                    Value = item.CategoryId.ToString(),
                    Text = item.Name,
                    Selected = item.CategoryId.ToString() == selectedValue
                }).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - GetCategoriesSelectList - Error: {ex.Message}");
            }
            return list;
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(Request model)
        {
            if (!User.Identity.IsAuthenticated)
                return BadRequest();
            try
            {
                var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                if (user == null)
                    return BadRequest();
                model.User = user;
                if (ModelState.IsValid)
                {
                    model.DateCreated = DateTime.Now;
                    model.UserId = user.Id;
                    model.IsActive = true;

                    user.Credits--;

                    _dbContext.Users.Update(user);
                    _dbContext.Requests.Add(model);
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {
                        model = await _dbContext.Requests.Include(s => s.Category).FirstOrDefaultAsync(s => s.RequestId == model.RequestId);
                        EmailHelper emailHelper = new EmailHelper(_settings)
                        {
                            ToAddress = user.Email,
                            ToAdressTitle = $"{user.FirstName} {user.LastName}"
                        };
                        emailHelper.SendRequestNotification(model);
                    }
                    return RedirectToAction("MyRequests");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - Add - Error: {ex.Message}");
            }
            ViewData["CategoryId"] = GetCategoriesSelectList(model.CategoryId.ToString());
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                Request request = await _dbContext.Requests.SingleAsync(m => m.RequestId == id);
                if (request == null)
                {
                    return NotFound();
                }
                ViewData["CategoryId"] = GetCategoriesSelectList(request.CategoryId.ToString());

                return View(request);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - Edit - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(Request model)
        {
            try
            {
                Request request = await _dbContext.Requests.SingleAsync(m => m.RequestId == model.RequestId);
                if (request == null)
                    return NotFound();
                if (ModelState.IsValid)
                {
                    request.Caption = model.Caption;
                    request.Credits = model.Credits;
                    request.Description = model.Description;
                    request.CategoryId = model.CategoryId;
                    request.DateEnd = model.DateEnd;
                    _dbContext.Update(request);
                    await _dbContext.SaveChangesAsync();
                    return RedirectToAction("MyRequests");
                }
                ViewData["CategoryId"] = GetCategoriesSelectList(request.CategoryId.ToString());
                return View("Edit", model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - Edit - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            try
            {
                Request request = await _dbContext.Requests.SingleAsync(m => m.RequestId == id);
                if (request == null)
                    return NotFound();
                return View(request);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - Delete - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                Request request = await _dbContext.Requests.Include(r => r.User).SingleAsync(m => m.RequestId == id);
                request.User.Credits++;
                request.IsActive = false;
                _dbContext.Requests.Update(request);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction("MyRequests");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Requests - Delete - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [Authorize]
        public async Task<IActionResult> GetRequest(int? id)
        {

TimeBankWebApplication/TimeBankWebApplication/Controllers/ResponsesController.cs
using Microsoft.AspNetCore.Mvc;
using TimeBankWebApplication.Models;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System;
using TimeBankWebApplication.Helpers;
using Microsoft.Extensions.Logging;

namespace TimeBankWebApplication.Controllers
{
    public class ResponsesController : Controller
    {
        private ApplicationContext _dbContext;
        private IOptions<AppSettings> _settings;
        private readonly ILogger<AccountController> _logger;

        public ResponsesController(ApplicationContext dbContext, IOptions<AppSettings> settings, ILogger<AccountController> logger)
        {
            _dbContext = dbContext;
            _settings = settings;
            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> MyResponses()
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    var user = await _dbContext.Users.Include(u => u.Orders).ThenInclude(o => o.Response)
                        .Include(d => d.Orders).ThenInclude(f => f.Service)
                        .Include(d => d.Orders).ThenInclude(f => f.Request)
                        .Include(d => d.Requests).ThenInclude(r => r.Orders).ThenInclude(o => o.Response)
                        .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                    if (user != null)
                    {
                        var responses = (from order in user.Orders
                                         where order.Response != null
                                         select order.Response).ToList();
                        var responsesRequests = (from request in user.Requests
                                                 where request.ActiveOrder != null 
                                                 && request.ActiveOrder.Response != null
                                                 select request.ActiveOrder.Response).ToList();
                        responses.AddRange(responsesRequests);
                        return View(responses);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Responses - MyResponses - Error: {ex.Message}");
                }
                return NotFound();
            }
            return NotFound();
        }

        [Authorize]
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                Order order = await _dbContext.Orders.Include(o => o.Response).FirstOrDefaultAsync(m => m.OrderId == id && m.Response == null);
                if (order == null)
                {
                    return NotFound();
                }
                var response = new Response
                {
                    OrderId = id
                };
                return View(response);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Responses - Create - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Response model)
        {
            if (!User.Identity.IsAuthenticated)
                return BadRequest();
            try
            {
                var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                if (user == null)
                    return BadRequest();
                if (ModelState.IsValid)
                {
                    model.DateCreated = DateTime.Now;
                    var order = await _dbContext.Orders.Include(o => o.Service).ThenInclude(s => s.User)
                        .Include(o => o.Request).ThenInclude(r => r.User)
                        .Include(o => o.User)
                        .FirstOrDefaultAsync(o => o.OrderId == model.OrderId);
                    if (order == null)
                        return BadRequest();
                    if (order.ServiceId != null)
                    {
                        //for service
                        var serviceOwner = order.User;
                        user.Credits -= model.Credits + 1;
                        serviceOwner.Credits += model.Credits;
                        _dbContext.Users.Update(serviceOwner);
                    }
                    else
                    {
                        //for request
                        user.Credits += model.Credits;
                        order.Request.User.Credits -= model.Credits + 1;
                        order.Request.IsDone = true;
                        _dbContext.Requests.Update(order.Request);
                        _dbContext.Users.Update(order.Request.User);
                    }
                    order.IsDone = true;
                    _dbContext.Users.Update(user);
                    order.Credits = model.Credits;
                    _dbContext.Orders.Update(order);
                    _dbContext.Responses.Add(model);
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {
                        EmailHelper emailHelper = new EmailHelper(_settings)
                        {
                            ToAddress = user.Email,
                            ToAdressTitle = $"{user.FirstName} {user.LastName}"
                        };
                        if (order.ServiceId != null)
                        {
                            var service = await _dbContext.Services.Include(s => s.Orders).ThenInclude(o => o.Response).FirstOrDefaultAsync(s => s.ServiceId == order.ServiceId);
                            CalculateRate(service);
                        }
                        model.Order = order;
                        emailHelper.SendResponseNotification(model);
                    }
                    return RedirectToAction("MyOrders", "Orders");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Responses - Create - Error: {ex.Message}");
            }
            return BadRequest();
        }

        private void CalculateRate(Service service)
        {
            try
            {
                var responses = from order in service.Orders
                                where order.Response != null
                                select order.Response;
                int sum = 0;
                foreach (var response in responses)
                {
                    sum += response.Rate;
                }
                double rate = (double)sum / responses.Count();
                service.Rate = Math.Round(rate, 2);
                _dbContext.Services.Update(service);
                _dbContext.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Responses - CalculateRate - Error: {ex.Message}");
            }
        }
    }
}

TimeBankWebApplication/TimeBankWebApplication/Views/Responses/Create.cshtml
@model TimeBankWebApplication.Models.Response
@{
    ViewData["Title"] = "Create Response";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">Add Response</h2>
                    <p>Leave a feedback for service</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-md-7 col-md-offset-2">
                    <form class="form-horizontal" role="form" asp-action="Create" asp-controller="Responses">
                        <input hidden asp-for="OrderId" />
                        <div class="form-group">
                            <label asp-for="Caption" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <input asp-for="Caption" class="form-control">
                                <span asp-validation-for="Caption" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Rate" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                @foreach (var item in Model.Rates)
                                {
                                    <input asp-for="Rate" type="radio" value="@item" /> @item
                                }
                                <span asp-validation-for="Rate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Credits" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <input asp-for="Credits" class="form-control">
                                <span asp-validation-for="Credits" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-11 col-sm-offset-1">
                            <input type="submit" class="btn btn-default" value="Add" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Responses/MyResponses.cshtml
@model IEnumerable<TimeBankWebApplication.Models.Response>
@{
    ViewData["Title"] = "My Responses";
}
<section id="blog">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">My Responses</h2>
                <p class="blog-heading">
                    @if (!Model.Any())
                    {
                        <div class="col-sm-12">You have no responses yet. Create one!</div>
                    }
                    <a asp-controller="Orders" asp-action="MyOrders">Orders</a>
                </p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-3">
                    <div class="single-blog">
                        <div class="rate">@item.Rate</div>
                        @if (item.Order.ServiceId != null)
                        {
                            <h2>@item.Order.Service.Caption</h2>
                        }
                        else if (item.Order.RequestId != null)
                        {
                            <h2>@item.Order.Request.Caption</h2>
                        }
                        <h4>@item.Caption</h4>
                        <ul class="post-meta">
                            <li><i class="fa fa-clock-o"></i><strong> Posted On:</strong> @item.DateCreated</li>
                        </ul>
                        <div class="blog-content">
                            <p>@item.Description</p>
                        </div>
                        @if (item.Order.ServiceId != null)
                        {
                            <a asp-controller="Services" asp-action="GetService" asp-route-id="@item.Order.ServiceId" class="btn btn-primary">Go to service</a>
                        }
                        else if (item.Order.RequestId != null)
                        {
                            <a asp-controller="Requests" asp-action="GetRequest" asp-route-id="@item.Order.RequestId" class="btn btn-primary">Go to request</a>
                        }
                    </div>
                </div>
            }
        </div>
    </div>
</section>