TimeBankWebApplication/TimeBankWebApplication/Models/Service.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TimeBankWebApplication.Models
{
    public class Service
    {
        public int ServiceId { get; set; }
        
        public int UserId { get; set; }

        [Required(ErrorMessage = "Category is required")]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Caption is required")]
        [MinLength(10, ErrorMessage = "Minimum length is 10")]
        [MaxLength(100, ErrorMessage = "Minimum length is 100")]
        public string Caption { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [MinLength(10, ErrorMessage = "Minimum length is 10")]
        public string Description { get; set; }

        [MaxLength(250)]
        public string ImageUrl { get; set; }

        [NotMapped]
        public IFormFile Image { get; set; }

        [Required(ErrorMessage = "Credits number is required")]
        [Range(1, 100, ErrorMessage = "Credits can be from 1 to 100")]
        [Display(Name = "Credits count")]
        public int Credits { get; set; }

        public DateTime DateCreated { get; set; }

        public double? Rate { get; set; }

        [Display(Name = "Is active")]
        public bool IsActive { get; set; }

        [Display(Name = "Why is not active")]
        [MinLength(10, ErrorMessage = "The minimum length is 10")]
        public string OffReason { get; set; }

        //Navigation properties
        public virtual List<Order> Orders { get; set; }
        public User User { get; set; }
        public Category Category { get; set; }
    }
}

TimeBankWebApplication/TimeBankWebApplication/Controllers/ServicesController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TimeBankWebApplication.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using TimeBankWebApplication.Helpers;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;

namespace TimeBankWebApplication.Controllers
{
    public class ServicesController : Controller
    {
        private const int _itemsOnPage = 8;
        private const int _pagesOnPagination = 5;
        private ApplicationContext _dbContext;
        private string[] _allowedExtensions;
        private IHostingEnvironment _environment;
        private IOptions<AppSettings> _settings;
        private readonly ILogger<ServicesController> _logger;

        public ServicesController(ApplicationContext dbContext, IHostingEnvironment environment,
            IOptions<AppSettings> settings, ILogger<ServicesController> logger)
        {
            _dbContext = dbContext;
            _environment = environment;
            _allowedExtensions = new[] { ".jpg", ".png"};
            _settings = settings;
            _logger = logger;
        }

        public async Task<IActionResult> AllServices(int? page)
        {
            List<Service> services = new List<Service>();
            List<User> users = new List<User>();
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    users = await _dbContext.Users.Include(u => u.Services)
                        .ThenInclude(s => s.Category).Where(u => u.UserName != User.Identity.Name).ToListAsync();
                }
                else
                    users = await _dbContext.Users.Include(u => u.Services)
                        .ThenInclude(s => s.Category).ToListAsync();
                services = (from user in users
                            from service in user.Services
                            where service.IsActive
                            select service).ToList();
            }
            catch(Exception ex)
            {
                _logger.LogError($"Services - AllServices - Error: {ex.Message}");
            }
            return GetPagination(page, services, "AllServices", null, false, "AllServices");
        }

        public async Task<IActionResult> Category(int? id, int? page)
        {
            if (id == null)
            {
                return BadRequest();
            }
            List<Service> services = new List<Service>();
            List<User> users = new List<User>();
            try
            {
                var category = _dbContext.Categories.FirstOrDefaultAsync(c => c.CategoryId == id).Result;
                if (category == null && id != 0)
                {
                    return BadRequest();
                }
                if (User.Identity.IsAuthenticated)
                {
                    users = await _dbContext.Users.Include(u => u.Services)
                        .ThenInclude(s => s.Category)
                        .Where(u => u.UserName != User.Identity.Name).ToListAsync();
                }
                else
                    users = await _dbContext.Users.Include(u => u.Services)
                        .ThenInclude(s => s.Category)
                        .ToListAsync();
                services = (from user in users
                            from service in user.Services
                            where service.IsActive
                            select service).ToList();
                if (id > 0)
                    services = services.Where(s => s.CategoryId == id).ToList();
                ViewBag.Title = id > 0 ? category.Name : "All";
                ViewBag.Category = category.Name;
                ViewBag.CategoryId = id;
            }
            catch (Exception ex)
            {
                _logger.LogError($"Services - AllServices - Error: {ex.Message}");
            }
            return GetPagination(page, services, "AllServices", id.ToString(), true, "ServicesPartialView");
        }

        [Authorize]
        public async Task<IActionResult> MyServices()
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    var user = await _dbContext.Users.Include(u => u.Services)
                        .ThenInclude(s => s.Category).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                    if (user != null)
                    {
                        return View(user.Services);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Services - MyServices - Error: {ex.Message}");
                }
                return NotFound();
            }
            return NotFound();
        }

        [Authorize]
        public async Task<IActionResult> GetService(int? id)
        {
            if (id == null)
                return BadRequest();
            Service service = null;
            User user = null;
            try
            {
                user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                service = await _dbContext.Services.Include(s => s.Category).Include(s => s.User)
                    .Include(s => s.Orders).ThenInclude(o => o.Response).FirstOrDefaultAsync(r => r.ServiceId == id);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Services - AllServices - Error: {ex.Message}");
            }
            if (service != null && user != null)
            {
                ViewBag.CurrentUserId = user.Id;
                return View(service);
            }
            return BadRequest();
        }

        [Authorize]
        public IActionResult Add()
        {
            ViewData["CategoryId"] = GetCategoriesSelectList();
            return View();
        }

        private List<SelectListItem> GetCategoriesSelectList(string selectedValue = null)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            try
            {
                list = _dbContext.Categories.Select(item => new SelectListItem
                {
                    Value = item.CategoryId.ToString(),
                    Text = item.Name,
                    Selected = item.CategoryId.ToString() == selectedValue
                }).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Services - GetCategoriesSelectList - Error: {ex.Message}");
            }
            return list;
        }

        private bool VerifyFileExtension(string path)
        {
            return _allowedExtensions.Contains(Path.GetExtension(path));
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(Service serviceModel)
        {
            if (!User.Identity.IsAuthenticated)
                return BadRequest();
            User user = null;
            try
            {
                user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Services - Add - Error: {ex.Message}");
            }
            if (user == null)
                return BadRequest();
            if (ModelState.IsValid)
            {
                var fileName = "";
                if (serviceModel.Image != null && serviceModel.Image.Length > 0)
                {
                    try
                    {
                        fileName =
                            ContentDispositionHeaderValue.Parse(serviceModel.Image.ContentDisposition).FileName.Trim('"');
                        if (VerifyFileExtension(fileName))
                        {
                            var uploads = Path.Combine(_environment.WebRootPath, "images");

                            var filePath = Path.Combine(uploads, fileName);
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                serviceModel.Image.CopyTo(fileStream);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("Image",
                                $"Image can be only with extensions: {_allowedExtensions.Join()}.");
                            ViewData["CategoryId"] = GetCategoriesSelectList(serviceModel.CategoryId.ToString());
                            return View(serviceModel);
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError($"Services - Add(saving image) - Error: {ex.Message}");
                    }
                }
                try
                {
                    var service = new Service
                    {
                        Caption = serviceModel.Caption,
                        Credits = serviceModel.Credits,
                        DateCreated = DateTime.Now,
                        Description = serviceModel.Description,
                        UserId = user.Id,
                        CategoryId = serviceModel.CategoryId,
                        ImageUrl = fileName == "" ? "/images/patterns/Services-Pattern.jpg" : $"/images/{fileName}",
                        IsActive = true
                    };
                    _dbContext.Services.Add(service);
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {

TimeBankWebApplication/TimeBankWebApplication/Views/Services/Add.cshtml
@model TimeBankWebApplication.Models.Service
@{
    ViewData["Title"] = "Add Service";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">Add Service</h2>
                    <p>Add your own service</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-md-7 col-md-offset-2">
                    <form class="form-horizontal" role="form" asp-action="Add" asp-controller="Services" enctype="multipart/form-data">
                        <div class="form-group">
                            <label asp-for="CategoryId" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <select asp-for="CategoryId" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["CategoryId"]))"></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Caption" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <input asp-for="Caption" class="form-control">
                                <span asp-validation-for="Caption" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Image" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <input type="file" asp-for="Image" class="form-control">
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Credits" class="col-sm-3 control-label"></label>
                            <div class="col-sm-8">
                                <input asp-for="Credits" class="form-control">
                                <span asp-validation-for="Credits" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-11 col-sm-offset-1">
                            <input type="submit" class="btn btn-default" value="Add" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Services/AllServices.cshtml
@model IEnumerable<TimeBankWebApplication.Models.Service>
@using TimeBankWebApplication.ViewComponents
@using TimeBankWebApplication.Helpers
@{
    ViewData["Title"] = "Services";
}
<section id="blog">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">All Services</h2>
                <p class="blog-heading">
                    @if (!Model.Any())
                    {
                        <div class="col-sm-12">We have no services yet.</div>
                    }
                </p>
            </div>
        </div>
        @await Component.InvokeAsync(nameof(Categories), 0)
        <div id="preloaderServices">
            <div class="preloder-wrap">
                <div class="preloder-inner">
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                </div>
            </div>
        </div>
        <div class="row dataBlock" id="servicesBlock">
            @Html.Partial("ServicesPartialView", Model)
        </div>
    </div>
    <div id="paginationBlock">
        @if (ViewBag.pager != null)
        {
            @await Component.InvokeAsync(nameof(Pagination), (Pager)ViewBag.pager);
        }
    </div>
</section>

@section scripts{
    <script>
        $(document).on('click', '.page', function (evt) {
            var selectedPage = $(evt.target);
            var pageId = selectedPage[0].id;
            var pageNumber = pageId.substr(5);
            hideItems();
            var selectedCategory = $("#categoryList .active")[0].id;
            var category = selectedCategory.substr(9);
            $("#servicesBlock").load("/Services/Category",
                { id: category, page: pageNumber }, function () {
                    refreshPaginationComponent(pageNumber, category);
                    showItems();
                });
        });
        function hideItems() {
            $("#servicesBlock").fadeOut("slow");
            $("#paginationBlock").fadeOut("slow");
            $("#preloaderServices").fadeIn("slow");
        };
        function showItems() {
            $("#preloaderServices").fadeOut("slow");
            $("#servicesBlock").fadeIn("slow");
            $("#paginationBlock").fadeIn("slow");
        };
        function refreshPaginationComponent(pageNumber, categoryId) {
            $("#paginationBlock").load("/Services/PaginationViewComponent",
                { page: pageNumber, action: "AllServices", routeCategory: categoryId });
        };
        $(document).ready(function () {
            $("#preloaderServices").fadeOut("slow");
            $(".category").click(function (evt) {
                hideItems();
                var selectedCategory = $(evt.target);
                var categoryId = selectedCategory[0].id.substr(9);
                var pageNumber = $("#pagination .active a").text();
                $("#servicesBlock").load("/Services/Category",
                    { id: categoryId, page: pageNumber }, function () {
                        refreshPaginationComponent(pageNumber, categoryId);
                        showItems();
                    });
            });
        });
    </script>
}

TimeBankWebApplication/TimeBankWebApplication/Views/Services/Delete.cshtml
@model TimeBankWebApplication.Models.Service
@{
    ViewData["Title"] = "Delete Service";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">Delete Service</h2>
                    <p>Are you sure you want to delete service "@Model.Caption"?</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-sm-9 col-sm-offset-2">
                    <form asp-action="Delete" class="form-horizontal" asp-controller="Services">
                        <div class="form-group">
                            <div class="col-sm-7 col-sm-offset-2">
                                <input type="submit" value="Yes" class="btn btn-default" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Services/Edit.cshtml
@model TimeBankWebApplication.Models.Service
@{
    ViewData["Title"] = "Edit Service";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">Edit Service</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-sm-9 col-sm-offset-2">
                    <form class="form-horizontal" role="form" asp-action="Edit" asp-controller="Services" enctype="multipart/form-data">
                        <input type="hidden" asp-for="ServiceId" />
                        <div class="form-group">
                            <label asp-for="CategoryId" class="col-sm-3 control-label"></label>
                            <div class="col-sm-9">
                                <select asp-for="CategoryId" class="form-control" asp-items="@((List<SelectListItem>) (ViewData["CategoryId"]))"></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Caption" class="col-sm-3 control-label"></label>
                            <div class="col-sm-9">
                                <input asp-for="Caption" class="form-control">
                                <span asp-validation-for="Caption" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-3 control-label"></label>
                            <div class="col-sm-9">
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input asp-for="ImageUrl" hidden />
                            <label asp-for="Image" class="col-sm-3 control-label"></label>
                            <div class="col-sm-9">
                                <input type="file" asp-for="Image" class="form-control">
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-9 col-sm-offset-3">
                                <img class="service-image" src="@Model.ImageUrl"
                                     alt="Service image"
                                     asp-append-version="true" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Credits" class="col-sm-3 control-label"></label>
                            <div class="col-sm-9">
                                <input asp-for="Credits" class="form-control">
                                <span asp-validation-for="Credits" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-default" value="Save" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Services/GetResponses.cshtml
@model TimeBankWebApplication.Models.Service
@{
    ViewData["Title"] = "Service Responses";
}
<section id="blog">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">Service Responses</h2>
                <p class="blog-heading">
                    @Html.ActionLink("Service", "GetService", "Services", new { id = Model.ServiceId })
                </p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in (from order in Model.Orders
                                  select order.Response))
            {
                <div class="col-sm-4">
                    <div class="single-blog">
                        <div class="rate">@item.Rate</div>
                        <h2>@item.Caption</h2>
                        <ul class="post-meta">
                            <li><i class="fa fa-clock-o"></i><strong> Posted On:</strong> @item.DateCreated</li>
                        </ul>
                        <div class="blog-content">
                            <p>@item.Description</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Services/GetService.cshtml
@model TimeBankWebApplication.Models.Service
@{
    ViewData["Title"] = "Service";
}
<section id="blog">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">Service</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-3">
                <div class="single-blog">
                    @if (@Model.Rate != null)
                    {
                        <div class="rate">@Model.Rate</div>
                    }
                    <img class="user-service-img" src="@Model.ImageUrl" alt="@Model.Caption" />
                    <h2>@Model.Caption</h2>
                    <ul class="post-meta">
                        <li><i class="fa fa-user"></i><strong> User:</strong> @Model.User.FirstName @Model.User.LastName</li>
                        <li><i class="fa fa-money"></i><strong> Credits:</strong> @Model.Credits</li>
                        <li><i class="fa fa-folder"></i><strong> Category:</strong> @Model.Category.Name</li>
                        <li><i class="fa fa-clock-o"></i><strong> Posted On:</strong> @Model.DateCreated</li>
                    </ul>
                    <div class="blog-content">
                        <p>@Model.Description</p>
                    </div>
                    @if (Model.IsActive)
                    {
                        if (Model.UserId != ViewBag.CurrentUserId)
                        {
                            <a asp-controller="Orders" asp-action="AddServiceOrder" asp-route-id="@Model.ServiceId" class="btn btn-primary">Want it!</a>
                        }
                    }
                    else
                    {
                        <div class="not-active-alert">This service is not active.</div>
                    }
                </div>
            </div>
            <div class="col-sm-4">
                <h3>Responses</h3>
                @if (Model.Orders.Any() && (from order in Model.Orders select order.Response != null).Count() > 0)
                {
                    <div class="list-group">
                        @foreach (var response in from order in Model.Orders where order.Response != null select order.Response)
                        {
                            <a class="list-group-item" href="#">
                                <div class="rate-list-item">@response.Rate</div>
                            @response.Description</a>
                        }
                    </div>
                }
                else
                {
                    <h4>There is no responses yet.</h4>
                }
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Services/MyServices.cshtml
@model IEnumerable<TimeBankWebApplication.Models.Service>
@{
    ViewData["Title"] = "My Services";
}
<section id="blog">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">My Services</h2>
                <p class="blog-heading">
                    @if (!Model.Any())
                    {
                        <div class="col-sm-12">You have no services yet. Create one!</div>
                    }
                    <a asp-controller="Services" asp-action="Add">Add Service</a>
                </p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <a asp-controller="Services" asp-action="GetService" asp-route-id="@item.ServiceId">
                    <div class="col-sm-3">
                        <div class="@(item.IsActive ? "single-blog" : "single-blog not-active")">
                            @if (@item.Rate != null)
                            {
                                <div class="rate">@item.Rate</div>
                            }
                            <img class="user-service-img" src="@item.ImageUrl" alt="@item.Caption" />
                            <h2>@item.Caption</h2>
                            <ul class="post-meta">
                                <li><i class="fa fa-user"></i><strong> User:</strong> @item.User.FirstName @item.User.LastName</li>
                                <li><i class="fa fa-money"></i><strong> Credits:</strong> @item.Credits</li>
                                <li><i class="fa fa-folder"></i><strong> Category:</strong> @item.Category.Name</li>
                                <li><i class="fa fa-clock-o"></i><strong> Posted On:</strong> @item.DateCreated</li>
                            </ul>
                            <div class="blog-content">
                                <p>@item.Description</p>
                            </div>
                            @if (item.IsActive) {
                                <a asp-controller="Services" asp-action="Edit" asp-route-id="@item.ServiceId" class="btn btn-primary">Edit</a>
                                <a asp-controller="Services" asp-action="Delete" asp-route-id="@item.ServiceId" class="btn btn-primary">Delete</a>
                            }
                            else
                            {
                                <div class="not-active-alert">This service is not active.</div>
                            }
                        </div>
                    </div>
                </a>
            }
        </div>
    </div>
</section>