TimeBankWebApplication/TimeBankWebApplication/Models/Order.cs
using System;

namespace TimeBankWebApplication.Models
{
    public class Order
    {
        public int OrderId { get; set; }

        public int UserId { get; set; }

        public int? ServiceId { get; set; }

        public int? RequestId { get; set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateDone { get; set; }
        
        public int Credits { get; set; }

        public bool IsActive { get; set; }

        public bool IsDone { get; set; }

        //Navigation properties
        public virtual Request Request { get; set; }
        public virtual Service Service { get; set; }
        public virtual Response Response { get; set; }
        public User User { get; set; }
    }
}

TimeBankWebApplication/TimeBankWebApplication/Controllers/OrdersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeBankWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using TimeBankWebApplication.Helpers;
using Microsoft.Extensions.Options;
using System;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;

namespace TimeBankWebApplication.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationContext _dbContext;
        private IOptions<AppSettings> _settings;
        private readonly ILogger<AccountController> _logger;

        public OrdersController(ApplicationContext dbContext, IOptions<AppSettings> settings,
                                 ILogger<AccountController> logger)
        {
            _dbContext = dbContext;
            _settings = settings;
            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> AddRequestOrder(int? id)
        {
            if (id == null)
                return BadRequest();
            try
            {
                var request = await _dbContext.Requests.FirstOrDefaultAsync(r => r.RequestId == id);

                if (request != null && User.Identity.IsAuthenticated)
                {
                    var user = await _dbContext.Users.Include(o => o.Orders).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                    if (user != null)
                    {
                        Order order = new Order
                        {
                            Request = request,
                            User = user,
                            RequestId = request.RequestId,
                            UserId = user.Id
                        };
                        return View(order);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Orders - AddRequestOrder - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SaveRequest(Order model)
        {
            if (!User.Identity.IsAuthenticated)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    _dbContext.Orders.Add(model);
                    model.DateCreated = DateTime.Now;
                    model.IsActive = true;
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {
                        model = await _dbContext.Orders.Include(s => s.Request).ThenInclude(c => c.Category)
                            .Include(s => s.Request).ThenInclude(u => u.User).Include(s => s.User)
                            .FirstOrDefaultAsync(s => s.OrderId == model.OrderId);
                        EmailHelper emailHelper = new EmailHelper(_settings)
                        {
                            ToAddress = model.Request.User.Email,
                            ToAdressTitle = $"{model.Request.User.FirstName} {model.Request.User.LastName}"
                        };
                        emailHelper.SendRequestOrderNotification(model);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Orders - SaveRequest - Error: {ex.Message}");
                }
                return RedirectToAction("MyOrders");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> AddServiceOrder(int? id)
        {
            if (id == null)
                return BadRequest();
            try
            {
                var service = await _dbContext.Services.FirstOrDefaultAsync(s => s.ServiceId == id);

                if (service != null && User.Identity.IsAuthenticated)
                {
                    var user = await _dbContext.Users.Include(o => o.Orders).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                    if (user != null)
                    {
                        Order order = new Order
                        {
                            Service = service,
                            User = user,
                            ServiceId = service.ServiceId,
                            UserId = user.Id
                        };
                        return View(order);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Orders - AddServiceOrder - Error: {ex.Message}");
            }
            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SaveService(Order model)
        {
            if (!User.Identity.IsAuthenticated)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    model.DateCreated = DateTime.Now;
                    model.IsActive = true;
                    _dbContext.Orders.Add(model);
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {
                        model = await _dbContext.Orders.Include(s => s.User)
                            .Include(s => s.Service).ThenInclude(c => c.Category)
                            .Include(s => s.Service).ThenInclude(u => u.User).Include(s => s.User)
                            .FirstOrDefaultAsync(s => s.OrderId == model.OrderId);
                        model.User.Credits--;
                        await _dbContext.SaveChangesAsync();
                        EmailHelper emailHelper = new EmailHelper(_settings)
                        {
                            ToAddress = model.Service.User.Email,
                            ToAdressTitle = $"{model.Service.User.FirstName} {model.Service.User.LastName}"
                        };
                        emailHelper.SendServiceOrderNotification(model);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Orders - SaveService - Error: {ex.Message}");
                }
                return RedirectToAction("MyOrders");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> MyOrders()
        {
            //All orders with services and requests
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    var user = await _dbContext.Users.Include(r => r.Orders).ThenInclude(o => o.Request)
                        .Include(r => r.Orders).ThenInclude(o => o.Response)
                        .Include(r => r.Orders).ThenInclude(o => o.Service).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                    if (user != null)
                    {
                        return View(user.Orders);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Orders - MyOrders - Error: {ex.Message}");
                }
                return NotFound();
            }
            return NotFound();
        }

        [Authorize]
        public async Task<IActionResult> DeleteRequest(int? id)
        {
            if (User.Identity.IsAuthenticated && id != null)
            {
                try
                {
                    Order order = await _dbContext.Orders.Include(o => o.Request).SingleAsync(m => m.OrderId == id && m.Request != null);
                    if (order == null)
                        return NotFound();
                    return View(order);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Orders - DeleteRequest - Error: {ex.Message}");
                }
            }
            return NotFound();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRequest(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    Order order = await _dbContext.Orders
                        .Include(s => s.Request).ThenInclude(c => c.Category)
                        .Include(s => s.Request).ThenInclude(u => u.User).Include(s => s.User)
                        .SingleAsync(m => m.OrderId == id);
                    order.IsActive = false;
                    _dbContext.Orders.Update(order);
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {
                        EmailHelper emailHelper = new EmailHelper(_settings)
                        {
                            ToAddress = order.Request.User.Email,
                            ToAdressTitle = $"{order.Request.User.FirstName} {order.Request.User.LastName}"
                        };
                        emailHelper.SendRequestOrderNotificationDelete(order);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Orders - DeleteRequest - Error: {ex.Message}");
                }
                return RedirectToAction("MyOrders");
            }
            return NotFound();
        }

        [Authorize]
        public async Task<IActionResult> DeleteService(int? id)
        {
            if (User.Identity.IsAuthenticated && id != null)
            {
                try
                {
                    Order order = await _dbContext.Orders.Include(o => o.Service).SingleAsync(m => m.OrderId == id && m.Service != null);
                    if (order == null)
                        return NotFound();
                    return View(order);
                }
                catch (Exception ex)
                {

TimeBankWebApplication/TimeBankWebApplication/Views/Orders/AddRequestOrder.cshtml
@model TimeBankWebApplication.Models.Order
@{
    ViewData["Title"] = "Request Order";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">@Model.Request.Caption</h2>
                    <p>If you want to help, just click next button</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-sm-8 col-sm-offset-2">
                    <form class="form-horizontal" role="form" asp-action="SaveRequest" asp-controller="Orders">
                        <input hidden asp-for="UserId" />
                        <input hidden asp-for="RequestId" />
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-default" value="Send" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Orders/AddServiceOrder.cshtml
@model TimeBankWebApplication.Models.Order
@{
    ViewData["Title"] = "Service Order";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">@Model.Service.Caption</h2>
                    <p>If you need help, just click next button</p>
                    <p>This service requires @Model.Service.Credits credits</p>
                    @if (Model.User.Credits < Model.Service.Credits)
                    {
                        <p class="attention">Your balance is @Model.User.Credits</p>
                        <p>You can't use this service. First of all you need to earn some credits.</p>
                        <p>To do this go to @Html.ActionLink("Requests", "AllRequests", "Requests") page or receive credits with your @Html.ActionLink("Services", "MyServices", "Services")</p>
                    }
                    @if (Model.User.IsActiveServiceOrder(Model.ServiceId))
                    {
                        <p>You have already ordrered this service. You can't order it again before you finish the previous.</p>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-sm-8 col-sm-offset-2">
                    <form class="form-horizontal" role="form" asp-action="SaveService" asp-controller="Orders">
                        <input hidden asp-for="UserId" />
                        <input hidden asp-for="ServiceId" />
                        <div class="col-md-6 col-md-offset-3">
                            <img class="service-order-image" src="@Model.Service.ImageUrl" />
                        </div>
                        <div class="col-sm-12">
                            @if (Model.User.Credits >= Model.Service.Credits && !Model.User.IsActiveServiceOrder(Model.ServiceId))
                            {
                                <input type="submit" class="btn btn-default" value="Send request" />
                            }
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Orders/DeleteRequest.cshtml
@model TimeBankWebApplication.Models.Order
@{
    ViewData["Title"] = "Refuse Request";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">Refuse Request</h2>
                    <p>Are you sure you want to refuse from performing this request: "@Model.Request.Caption"?</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-sm-7 col-sm-offset-2">
                    <form asp-action="DeleteRequest" class="form-horizontal" asp-controller="Orders">
                        <div class="form-group">
                            <div class="col-sm-5 col-sm-offset-4">
                                <input type="submit" value="Yes" class="btn btn-default" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Orders/DeleteService.cshtml
@model TimeBankWebApplication.Models.Order
@{
    ViewData["Title"] = "Refuse Service";
}
<section id="contact">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="contact-heading">
                    <h2 class="title-one">Refuse from Service</h2>
                    <p>Are you sure you want to refuse from this service: "@Model.Service.Caption"?</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="contact-details">
            <div class="row text-center clearfix">
                <div class="col-sm-7 col-sm-offset-2">
                    <form asp-action="DeleteService" class="form-horizontal" asp-controller="Orders">
                        <div class="form-group">
                            <div class="col-sm-5 col-sm-offset-4">
                                <input type="submit" value="Yes" class="btn btn-default" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

TimeBankWebApplication/TimeBankWebApplication/Views/Orders/MyOrders.cshtml
@model IEnumerable<TimeBankWebApplication.Models.Order>
@{
    ViewData["Title"] = "Orders";
}
<section id="blog">
    <div class="container">
        <div class="row text-center clearfix">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">My Orders</h2>
                <p class="blog-heading">
                    @if (!Model.Any())
                    {
                        <div class="col-sm-12">You have no orders yet. Go to @Html.ActionLink("Services", "Services", "AllServices") or @Html.ActionLink("Requests", "Requests", "AllRequests") to create one!</div>
                    }
                </p>
            </div>
        </div>
        <ul class="portfolio-filter text-center orders-filter">
            <li><a class="btn btn-default active" href="#" id="orders-all">All</a></li>
            <li><a class="btn btn-default" href="#" id="orders-services">Services</a></li>
            <li><a class="btn btn-default" href="#" id="orders-requests">Requests</a></li>
            <li><a class="btn btn-default" href="#" id="orders-active">Active</a></li>
            <li><a class="btn btn-default" href="#" id="orders-notactive">Not active</a></li>
            <li><a class="btn btn-default" href="#" id="orders-isdone">Is done</a></li>
            <li><a class="btn btn-default" href="#" id="orders-isnotdone">Is not done</a></li>
        </ul>
        <div id="preloaderOrders">
            <div class="preloder-wrap">
                <div class="preloder-inner">
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                    <div class="ball"></div>
                </div>
            </div>
        </div>
        <div class="row" id="ordersBlock">
            @Html.Partial("OrdersPartialView", Model)
        </div>
    </div>
</section>
@section scripts{
    <script>
        function hideItems() {
            $("#ordersBlock").fadeOut("slow");
            $("#preloaderOrders").fadeIn("slow");
        };
        function showItems() {
            $("#preloaderOrders").fadeOut("slow");
            $("#ordersBlock").fadeIn("slow");
        };
        $(document).ready(function () {
            $("#preloaderOrders").fadeOut("slow");
            $(".orders-filter a").click(function (evt) {
                $(".orders-filter a").removeClass("active");
                $(this).addClass('active');
                hideItems();
                var selectedCategory = $(evt.target);
                selectedCategory
                var categoryId = selectedCategory[0].id;
                $("#ordersBlock").load("/Orders/Category",
                    { id: categoryId }, function () {
                        showItems();
                    });
            });
        });
    </script>
}